project:
  type: website

website:
  favicon: images/profile.png
  title: "A Quarto tip a day"
  site-url: https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day
  description: 'Inspired by the saying "An apple a day keeps the doctor away", this project titled "A Quarto tip a day keeps the docs away" is a playful attempt to share Quarto tips for a month leading up to my rstudio::conf(2022) keynote on Quarto.'
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: rss-fill
        href: index.xml
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/quarto-tip-a-day
      - icon: twitter
        href: https://twitter.com/quarto_pub

  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Mine Çetinkaya-Rundel"
    background: "#F8F9FA"

format:
  html:
    theme:
      - litera
      - styles.scss
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap

editor: visual
