---
title: "Title-less slides"
date: "2022-07-20"
categories: [presentation, revealjs]
image-alt: "Add slide title."
---

Most slides are comprised of a title and content, but sometimes you might choose to not have a title for a slide. 

For example, if you just want to a full slide image or want to show an impactful quote on a slide with nothing else. You can have title-less slides in Quarto, but if you want those slides to appear properly in the presentation outline you'll need to do the following:

- Define a slide ID with `#slide-id` to be used as the slug in the slide URL.
- Define `data-menu-title = "Slide title"` to be used in the presentation outline.

Here is a sample slide deck with three slides:

- Slide 1 has a title and content.
- Slide 2 has no title but content.
- Slide 3 also has no title but content, but also defines a slide ID and `data-menu-title`.

```{=html}
<iframe width="800px" height="533px" style="border:2px solid #dee2e6;" src="titleless.html"></iframe>
```

Check out the presentation outline by clicking on the hamburger menu (the three lines) at the bottom left of the slides as well and open the slides in a new tab/window to review the slide URLs: [add url].

A couple more notes on slide titles:

-  You can choose to have slide numbers instead of slugs based on slide IDs show up in the URL by setting `hash-type: number`.

``` yaml
format:
  revealjs:
    hash-type: number
```

- If your slide has no title and no text content (e.g., you only have a picture on the slide) but has speaker notes, the document outline will show the speaker notes if you don't define `data-menu-title`. You probably don't want that...

## Learn more

- [Creating slides](https://quarto.org/docs/presentations/powerpoint.html#creating-slides)
- [Revealjs options](https://quarto.org/docs/reference/formats/presentations/revealjs.html)
