---
format: 
  revealjs:
    chalkboard: true
    mainfont: "Atkinson Hyperlegible"
    controls: false
toc: false
execute: 
  echo: fenced
editor: visual
---

## Slide 1 title

Slide 1 content - this slide has a title:

✅ Check out the URL of the slide -- the slide title is the slug in the URL

✅ Check out the presentation outline in the hamburger menu - the slide title also shows up there

## 

Slide 2 content - this slide has no title:

❌ Check out the URL of the slide -- the slide doesn't have an informative slide `id` that's used as the slug in the URL

❌ Check out the presentation outline in the hamburger menu -- the slide doesn't have an informative title, instead content from the slide is abbreviated as placeholder

##  {#slide3-id data-menu-title="Slide 3 title for outline"}

Slide 3 content - this slide has no title, but has the following defined in the title instead:

✅ `#slide3-id` - which shows up in the URL for the slide

✅ `data-menu-title="Slide 3 title for outline"` - which shows up in the presentation outline in the hamburger menu on the slides
