---
format: 
  revealjs:
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-dark
toc: false
execute: 
  echo: fenced
editor: visual
---

## default

```{r}
#| echo: false

library(tidyverse)
library(palmerpenguins)
library(colorblindr)
```

```{r}
#| fig-alt: |
#|   Scatterplot of penguin bill depth vs. length, colored by species.
#|   The relationship is positive for each of the three species.

ggplot(penguins, 
       aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() +
  scale_color_OkabeIto()
```

## `fragment`

```{r}
#| output-location: fragment

ggplot(penguins, 
       aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() +
  scale_color_OkabeIto()
```

## `slide`

```{r}
#| output-location: slide

ggplot(penguins, 
       aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() +
  scale_color_OkabeIto()
```

## `column`

```{r}
#| output-location: column
#| fig-width: 6
#| fig-height: 4

ggplot(penguins, 
       aes(x = bill_length_mm, 
           y = bill_depth_mm, 
           color = species)) +
  geom_point() +
  scale_color_OkabeIto()
```

## `column-fragment`

```{r}
#| output-location: column-fragment
#| fig-width: 6
#| fig-height: 4

ggplot(penguins, 
       aes(x = bill_length_mm, 
           y = bill_depth_mm, 
           color = species)) +
  geom_point() +
  scale_color_OkabeIto()
```
